---
title: "Gulsah Gurkan's resume"
author: Gulsah Gurkan
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    #css: 'styles.css'
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: false
# uncomment this line to produce HTML and PDF in RStudio:
knit: pagedown::chrome_print
---

```{css, echo=FALSE}

* {
  --pagedjs-margin-top: 0.5in;
  --pagedjs-margin-bottom: 0.2in;
  --pagedjs-margin-right: 0.2in;
  --pagedjs-margin-left: 0.3in;
}

.pagedjs_page:not(:first-of-type) {
  --main-width: calc(var(--content-width) - var(--sidebar-width));
  --decorator-horizontal-margin: 0.2in;
  --sidebar-width: 0.1rem;
  --sidebar-background-color: white;
}


:root {
  --sidebar-width: 12rem; 
  --sidebar-background-color: #F7F7F7;
  --sidebar-horizontal-padding: 0.01in; 
  --decorator-outer-dim: 10px; 
  --decorator-border: 2px solid #1565c0;
}

.decorator::after {
  background-color: #bfbbbb;
}

a {
  color: #1565c0;
}

.aside {
  margin-top: 0.5in;
  line-height: 1.2;
  font-size: 0.75rem;
}

.blocks {
  break-inside: avoid;
}

.fa-laptop {
  margin-left: -3px;
  margin-top: 2px;
}
.fa-chalkboard-teacher {
  margin-left: -2px;
  margin-top: 2px;
}
.fa-file {
  margin-left: 2px;
  margin-top: 2px;
}

h1 {
  text-transform: unset;
}

```


# Aside

### Contact {#contact}

- <i class="fa fa-envelope"></i> gurkangulsah@gmail.com
- <i class="fas fa-link"></i> [gulsah-gurkan.com](https://www.gulsah-gurkan.com/)
- <i class="fa fa-github"></i> [\@Gulsah-G](https://github.com/Gulsah-G)
- <i class="fa fa-linkedin"></i> [\@gurkangulsah](https://www.linkedin.com/in/gurkangulsah/)
- <i class="fa fa-twitter"></i> [\@GulsahGurkan_](https://twitter.com/GulsahGurkan_)




&nbsp; 



### Skills {#skills}

- **Areas of Expertise:**
  - Quantitative methodology
  - Advanced statistical modeling
  - Experimental design
  - Causal inference
  - Psychometrics
  - Survey design and research
  
  
- **Computing:**
  - **Statistical:** R, SPSS Syntax, HLM, mdltm, LISREL, IRTPRO, WINSTEPS.
  - **Databases:** SQL, RMySQL, GitHub.
  - **Survey platforms:** Qualtrics, Google Forms.





## Disclaimer {#disclaimer}

Made with the R package [**pagedown**](https://github.com/rstudio/pagedown).
Last updated on `r Sys.Date()`.



# Main

## Gulsah Gurkan {#title}

### Applied Statistician | Psychometrician | Data Scientist


## Education {data-icon=graduation-cap}

### PhD, Measurement, Evaluation, Statistics, and Assessment

Boston College

Chestnut Hill, MA

2021

Dissertation: "From OLS to Multilevel Multidimensional Mixture IRT: A Model Refinement Approach to Investigating Patterns of Relationships in PISA 2012 Data"

Committee: Henry Braun (chair), Matthias von Davier, Michael Martin, Zhushan Li


### Integrated BSc. & MSc., Teaching Physics 

Bogazici University

Istanbul, Turkey

2011

(Dual Degree in Physics and Secondary School Science & Mathematics Education)


&nbsp;


## Professional Experience {data-icon=suitcase}

### Kaplan North America

_Psychometrician_

Remote

Present - March 2021

- Leading and executing projects to evaluate the efficacy of online test preparation products on academic and career outcomes.
- Building statistical models and communicating recommendations to product leaders for improvement.
- Developing programming and documentation in R and R Markdown to automate data processing, analysis, and reporting procedures.
- Providing expertise for research design and advanced statistical modeling techniques primarily used in quasi-experimental design.



### Boston College

_Graduate Statistical Consultant (Research Services)_

Remote

February 2021 - September 2020

- Provided consultations and tutorials to faculty and students from various departments to support their statistical computing and quantitative research.
- Assisted with selecting methodologies, planning and performing statistical data analysis, data management, and statistical computing.


_Graduate Assistant (Institutional Research and Planning)_

- Assisted with analysis and reporting of data from campus-wide surveys, which were used to monitor trends and provide feedback about various programs and campus issues.
- Automated data cleaning and wrangling processes for annually published internal dashboards.



### uAspire

_Chewning Research Fellow_

Remote

September 2020 - July 2020

- Designed and executed research projects to examine the organization's impact on college affordability/access and advance their learning for further program development and implementation.
- Employed data from multiple databases, conducted statistical analyses, and presented research findings to diverse audiences.


### Educational Testing Service

_Research Intern_

Princeton, NJ

Summer 2020

- Proposed project: The investigation of alternative RMSD statistics for international large-scale assessments.
-- _Canceled due to COVID-19._



### Boston College
_Research Assistant (Center for the Study of Testing, Evaluation, and Educational Policy)_

Chestnut Hill, MA

July 2020 - September 2015

- Conducted quasi-experimental studies employing both longitudinal and cross-sectional data from complex survey design studies.
- Analyzed data using various procedures such as generalized linear models, multilevel models, cluster analysis, inverse probability weighting.
- Conducted psychometric analyses to develop and validate instruments measuring both cognitive and non-cognitive constructs.
- Automated data analysis and reporting procedures in R and R Markdown to be shared with stakeholders.
- Assisted with organizing a 2.5-day conference and interactive workshop on the challenges with measuring hard-to-measure constructs.




### Kaplan Test Prep

_Psychometrician Intern_

New York, NY

Summer 2019 

- Conducted an empirical simulation study to examine the feasibility and sustainability of automated test assembly methods to personalize online assessment products to each user’s needs.
- Developed an R package for automated test assembly ('[**ata**](https://cran.r-project.org/web/packages/ata/ata.pdf)' available on CRAN R repository).


### New York City Department of Education

_Data Analyst | Education Pioneers Summer Fellow_

New York, NY

Summer 2018  

- Built a dashboard to communicate the impact of a professional development program to 45 superintendents and 9 Field Support Centers in New York City.
- Developed visuals in R including mapping attendance data to geographically demonstrate the participation rates by NYC districts to be shared externally.
- Contributed to the team’s ongoing work to refine the program logic model and design evaluation studies.


### Dublin City University

_Research Associate_

Dublin, Ireland

Summer 2017  

- Developed and validated a scale measuring students’ physical and emotional well-being.
- Conducted psychometric analyses employing factor analytic approaches and Rasch modeling.


### Educational Volunteers Foundation of Turkey (TEGV)

_Measurement and Evaluation Specialist_

Istanbul, Turkey

June 2015 - June 2012

- Coordinated measurement and evaluation studies to determine the effectiveness of more than 10 education programs across 30 cities in the underdeveloped provinces of Turkey.
- Developed measurement tools such as student questionnaires, interview and observation protocols.
- Collected, analyzed, and reported data for the purposes of organizational monitoring.
- Devised research briefs and reports on various aspects of education policy issues in Turkey.
- Represented the organization in “Volunteerism: Measuring Global Impact II” workshop that took place in June 2015 in Nairobi, Kenya. 





## Teaching Experience {data-icon=chalkboard-teacher}

### Fordham University

_Workshop Host_

New York, NY

February 2020

- Automated Test Assembly in R (with Michael Chajewski)


### Boston College

_Teaching Assistant_

Chestnut Hill, MA

May 2019 - September 2018

- Multivariate Statistics (Instructor: Zhushan Li)
- Psychometric Theory II – Item Response Theory (Instructor: Zhushan Li)



## Software / Statistical Packages {data-icon=cube}

###

**Gurkan, G.**, Chajewski, M. (2020). ata: Automated test assembly. (Version 1.1.0). R software package: The R Project for Statistical Computing.

N/A




## Selected Publications and Conference Presentations {data-icon=file}

###

**Gurkan, G.**, Benjamini, Y., Braun, H. (2021). Defensible inferences from a nested sequence of logistic regressions: a guide for the perplexed. _Large-scale Assessment in Education, 9_(16). doi: 10.1186/s40536-021-00111-7

N/A


###

**Gurkan, G.**, von Davier, M., Braun, H. (2020). Accounting for measurement error and clustering in cross-cultural assessment data. _Presentation given at the (Virtual) International Meeting of the Psychometric Society_.

N/A


###

**Gurkan, G.**, von Davier, M., Braun, H. (2020). On the cross-country heterogeneity of within-country bivariate relationships in international large-scale assessments: understanding, evaluating and adjusting for the contributions of measurement error and clustering. _Paper accepted to the 12th Conference of the International Test Commission, in Luxembourg City, Luxembourg_.

N/A


###

**Gurkan, G.**, Chajewski, M. (2020). Exploring online assessment personalization via automated test assembly. _Paper accepted to the annual meeting of the National Council on Measurement in Education, in San Francisco, CA_.

N/A


###

**Gurkan, G.** (2019). A multilevel modeling analysis to investigate the factors affecting Turkish students’ scientific literacy performance in PISA 2015. _Presentation given at the annual meeting of the New England Educational Research Organization, in Portsmouth, NH_.

N/A


###

**Gurkan, G.**, Luna Bazaldua, D., & Braun, H. (2018). Testing dynamic complementarity in educational opportunities to accumulate relevant human capital. _Presentation given at the annual meeting of the National Council on Measurement in Education, in New York, NY_.

N/A


###

**Gurkan, G.** (2017). Psychometric properties of Learning to Teach for Social Justice Practices scale. _Presentation given at the annual meeting of the New England Educational Research Organization, in Portsmouth, NH_.

N/A


#


```{css, echo=FALSE}
[data-id="disclaimer"] {
  font-size: 0.7rem;
}

[data-id="disclaimer"] p {
  margin-bottom: -0.5in;
}

# [data-id="skills"] {
#     line-height: 1.5;
# }

* {
  font-family: "Palatino Linotype", "Times New Roman", Palatino, serif;
  # font-weight: 300;
  # line-height: 1.3;
  # color: #444;
}

```




